import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({ results }) {
  // console.log(results)

  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      {/* pass 'results' that was destructured from 'props' to the Results component */}
      <Results results={results} />
    </div>
  )
}

/**
 * getServerSideProps comes with 'context' object which contains the url user came from and other useful information
 * this function will run BEFORE the 'Home' component is rendered as the server render happens before the client (frontend) render
 * the getServerSideProps function is run and then passes props the the 'Home' component
 */
export async function getServerSideProps(context) {
  // pull genre from the url
  const genre = context.query.genre

  // make request to api
  const req = await fetch(
    `https://api.themoviedb.org/3${
        requests[genre]?.url || requests.fetchTrending.url
      }`
    ).then((res) => res.json())

    // once it request renders on the server -- return data as props to be passed to component
    return {
      props: {
        results: req.results,
      }
    }
}